// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fc-sistemas-monoliticos/internal/store-catalog/usecase/port (interfaces: FindProductUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/store-catalog/usecase/find_product.go -package=mocks github.com/fc-sistemas-monoliticos/internal/store-catalog/usecase/port FindProductUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	port "github.com/fc-sistemas-monoliticos/internal/store-catalog/usecase/port"
	gomock "go.uber.org/mock/gomock"
)

// MockFindProductUseCase is a mock of FindProductUseCase interface.
type MockFindProductUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFindProductUseCaseMockRecorder
	isgomock struct{}
}

// MockFindProductUseCaseMockRecorder is the mock recorder for MockFindProductUseCase.
type MockFindProductUseCaseMockRecorder struct {
	mock *MockFindProductUseCase
}

// NewMockFindProductUseCase creates a new mock instance.
func NewMockFindProductUseCase(ctrl *gomock.Controller) *MockFindProductUseCase {
	mock := &MockFindProductUseCase{ctrl: ctrl}
	mock.recorder = &MockFindProductUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFindProductUseCase) EXPECT() *MockFindProductUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockFindProductUseCase) Execute(input port.FindProductInputDTO) (port.FindProductOutputDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", input)
	ret0, _ := ret[0].(port.FindProductOutputDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockFindProductUseCaseMockRecorder) Execute(input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockFindProductUseCase)(nil).Execute), input)
}
