// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fc-sistemas-monoliticos/internal/store-catalog/usecase/port (interfaces: FindAllProductsUseCase)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/store-catalog/usecase/find_all_products.go -package=mocks github.com/fc-sistemas-monoliticos/internal/store-catalog/usecase/port FindAllProductsUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	port "github.com/fc-sistemas-monoliticos/internal/store-catalog/usecase/port"
	gomock "go.uber.org/mock/gomock"
)

// MockFindAllProductsUseCase is a mock of FindAllProductsUseCase interface.
type MockFindAllProductsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFindAllProductsUseCaseMockRecorder
	isgomock struct{}
}

// MockFindAllProductsUseCaseMockRecorder is the mock recorder for MockFindAllProductsUseCase.
type MockFindAllProductsUseCaseMockRecorder struct {
	mock *MockFindAllProductsUseCase
}

// NewMockFindAllProductsUseCase creates a new mock instance.
func NewMockFindAllProductsUseCase(ctrl *gomock.Controller) *MockFindAllProductsUseCase {
	mock := &MockFindAllProductsUseCase{ctrl: ctrl}
	mock.recorder = &MockFindAllProductsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFindAllProductsUseCase) EXPECT() *MockFindAllProductsUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockFindAllProductsUseCase) Execute() ([]port.FindAllProductsOutputDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].([]port.FindAllProductsOutputDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockFindAllProductsUseCaseMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockFindAllProductsUseCase)(nil).Execute))
}
